#include "tMotor.h"

/* INITIALISE COUNTER FOR MOTOR COMPONENT */
void initMotorPWM(void) {
	
	SIM->SOPT2 &= ~SIM_SOPT2_TPMSRC_MASK;	
	SIM->SOPT2 |= SIM_SOPT2_TPMSRC(1);
	
	TPM1->SC &= ~(TPM_SC_CPWMS_MASK|TPM_SC_CMOD_MASK|TPM_SC_PS_MASK);
	TPM1->SC |= (TPM_SC_CMOD(1)|TPM_SC_PS(7));
	
	TPM2->SC &= ~(TPM_SC_CPWMS_MASK|TPM_SC_CMOD_MASK|TPM_SC_PS_MASK);
	TPM2->SC |= (TPM_SC_CMOD(1)|TPM_SC_PS(7));
	
	TPM1_C1SC  &= ~(TPM_CnSC_ELSA_MASK |TPM_CnSC_ELSB_MASK | TPM_CnSC_MSA_MASK |TPM_CnSC_MSB_MASK);
	TPM1_C0SC  &= ~(TPM_CnSC_ELSA_MASK |TPM_CnSC_ELSB_MASK | TPM_CnSC_MSA_MASK |TPM_CnSC_MSB_MASK);
	
	TPM2_C1SC  &= ~(TPM_CnSC_ELSA_MASK |TPM_CnSC_ELSB_MASK | TPM_CnSC_MSA_MASK |TPM_CnSC_MSB_MASK);
	TPM2_C0SC  &= ~(TPM_CnSC_ELSA_MASK |TPM_CnSC_ELSB_MASK | TPM_CnSC_MSA_MASK |TPM_CnSC_MSB_MASK);
	
	TPM1_C1SC |=(TPM_CnSC_ELSB(1)|TPM_CnSC_MSB(1));    
	TPM1_C0SC |=(TPM_CnSC_ELSB(1)|TPM_CnSC_MSB(1)); 
	
	TPM2_C1SC |=(TPM_CnSC_ELSB(1)|TPM_CnSC_MSB(1));    
	TPM2_C0SC |=(TPM_CnSC_ELSB(1)|TPM_CnSC_MSB(1)); 
	
}

/* INITIALISE  MOTOR COMPONENT */
//set modulo value 48000000/128 = 375000, 375000Hz/100Hz = 3750	
void initMotor(void) {

  PORTB->PCR[PTB1] &= ~PORT_PCR_MUX_MASK;
  PORTB->PCR[PTB1] |= PORT_PCR_MUX(3);//TPM1CH1
	PORTB->PCR[PTB0] &= ~PORT_PCR_MUX_MASK;
  PORTB->PCR[PTB0] |= PORT_PCR_MUX(3);//TPM1CH0
	
	PORTB->PCR[PTB3] &= ~PORT_PCR_MUX_MASK;
  PORTB->PCR[PTB3] |= PORT_PCR_MUX(3);//TPM2CH1
	PORTB->PCR[PTB2] &= ~PORT_PCR_MUX_MASK;
  PORTB->PCR[PTB2] |= PORT_PCR_MUX(3);//TPM2CH0
	
  PTB->PDDR |= (MASK(PTB1));
	PTB->PDDR |= (MASK(PTB0));
	
	PTB->PDDR |= (MASK(PTB3));
	PTB->PDDR |= (MASK(PTB2));

}

/* FORWARD */
void fw(void) {
	TPM1->MOD = TPMMOD;
	TPM2->MOD = TPMMOD;
	
	TPM1_C0V = TPMMOD;
	TPM2_C1V = TPMMOD;
	
	TPM2_C0V = 0;
	TPM1_C1V = 0;
}

/* REVERSE */
void rv(void) {
	TPM1->MOD = TPMMOD;
	TPM2->MOD = TPMMOD;
	
	TPM1_C1V = TPMMOD;
	TPM2_C0V = TPMMOD;
	
	TPM1_C0V = 0;
	TPM2_C1V = 0;	
}

/* FORWARD LEFT CURVE  */
void leftForward(void) {
	TPM1->MOD = TPMMOD;
	TPM2->MOD = TPMMOD;
		
	TPM1_C1V = 0;
	TPM2_C0V = 0;
	
	TPM1_C0V = TPMMOD;
	TPM2_C1V = 0;
}

/* FORWARD RIGHT CURVE */
void rightForward(void) {
	TPM1->MOD = TPMMOD;		
	TPM2->MOD = TPMMOD;
	
	TPM1_C1V = 0;
	TPM2_C0V = 0;
	
	TPM1_C0V = 0;
	TPM2_C1V = TPMMOD;
}

/* REVERSE LEFT CURVE */
void leftReverse(void){
	TPM1->MOD = TPMMOD;
	TPM2->MOD = TPMMOD;
		
	TPM1_C1V = TPMMOD;
	TPM2_C0V = 0;
	
	TPM1_C0V = 0;
	TPM2_C1V = 0;
}

/* REVERSE RIGHT CURVE */
void rightReverse(void){
	TPM1->MOD = TPMMOD;		
	TPM2->MOD = TPMMOD;
	
	TPM1_C1V = 0;
	TPM2_C0V = TPMMOD;
	
	TPM1_C0V = 0;
	TPM2_C1V = 0;
}

/* TURN MOTORS OFF */
void offMotors(void) {
	TPM1->MOD = 0;
	TPM2->MOD = 0;
	
	
	TPM1_C0V = 0;
	TPM1_C1V = 0;
	TPM2_C0V = 0;
	TPM2_C1V = 0;
}

/* ROTATE LEFT */
void leftSharp(void){
	TPM1->MOD = TPMMOD;		
	TPM2->MOD = TPMMOD;

	TPM1_C1V = 0;
	TPM2_C0V = TPMMOD;
	
	TPM1_C0V = TPMMOD;
	TPM2_C1V = 0;
}

/* ROTATE RIGHT */
void rightSharp(void) {
	TPM1->MOD = TPMMOD;
	TPM2->MOD = TPMMOD;
		
	TPM1_C1V = TPMMOD;
	TPM2_C0V = 0;
	
	TPM1_C0V = 0;
	TPM2_C1V = TPMMOD;
}

// RESERVED ONLY FOR SELF-DRIVING MODE
// PERFORMS A CIRCULAR LOOP
void rightCircle(void) {
	TPM1->MOD = TPMMOD;		
	TPM2->MOD = TPMMOD;
	
	TPM1_C1V = TPMMOD/2;
	TPM2_C0V = 0;
	
	TPM1_C0V = TPMMOD;
	TPM2_C1V = TPMMOD;
}



